### ISSUE TITLE
Unable to replicate results on tieredImageNet

### ISSUE THREAD

**Issue by YihaoChen96** [Yikai-Wang/ICI-FSL#10]
Dear Yikai,

Congrats on paper acceptance and appreciate that you make the code available. I was trying to replicate the results using your pre-trained tieredImageNet model but the results I got were around 20% lower than your reported results. Do you know what could have been the issue? Could you please share the csv files that you were training with? Thanks!

Best,
Yihao

**Comment by Yikai-Wang** [comment]
The tieredImageNet we used is downloaded from [here](https://github.com/yaoyao-liu/meta-transfer-learning). You may check if the gap is due to the dataset.

**Comment by YihaoChen96** [comment]
Thank you! I will go ahead and have a look.
