### ISSUE TITLE
The pretrained models cannot be decompressed

### ISSUE THREAD

**Issue by plzhong309** [Yikai-Wang/ICI-FSL#12]
Hi,Thanks for your exciting work.
I've downloaded the code you provided, but the pretrained model can't be decompressed, can you send me an uncompressed version of the pretrained model?
Thank you!

**Comment by Yikai-Wang** [comment]
You do not need to decompress the model. Just download it and run the code with 
`
--resume $PATH_OF_THE_MODEL
`
