### ISSUE TITLE
Better experimental results on the CIFAR-FS dataset

### ISSUE THREAD

**Issue by lampardwk** [Yikai-Wang/ICI-FSL#14]
Many thanks for making the latest code available. I am trying to run the experiments from scratch, but I am getting around +4% more accuracy on the CIFAR-FS dataset while I get similar accuracy for the rest of the datasets. The parameters in all experiments are strictly based on the description in the paper. I was wondering if this is normal and what may cause this problem.
Thanks in advance.

**Comment by Yikai-Wang** [comment]
Hi there,
thanks for the attention to our work.
As you can reproduce experiments on the other datasets, the only reason seems to be the dataset. Did you try to use different random seed? 
Compared to other datasets, CIFAR-FS is a low resolution image dataset, which may be more sensitive to random seeds. Besides, please note that we resize all the images into 84 X 84 pixels.
Hope it can help you.

**Comment by lampardwk** [comment]
Many thanks on your quick reply. I'll repeat the experiment according to your suggestion.
