### ISSUE TITLE
split setting of miniImagenet

### ISSUE THREAD

**Issue by Johnzhjw** [Yikai-Wang/ICI-FSL#18]
miniImageNet_category_split_train_phase_train.pickle
miniImageNet_category_split_val.pickle
miniImageNet_category_split_test.pickle
Cannot find these three files, how to find them?

**Comment by Yikai-Wang** [comment]
As we said in [dataset preparation](https://github.com/Yikai-Wang/ICI-FSL/tree/master/V2-TPAMI#dataset-preparation) part, you can download it from the corresponding links.

**Comment by Johnzhjw** [comment]
I can only download the tieredImageNet dataset from BaiduNetDisk, while other the provided links to other datasets cannot be accessed.
Please provide the BaiduNetDisk links.
Thanks.

**Comment by Johnzhjw** [comment]
Excuse me, another question.
In Table 2 of paper ``How to Trust Unlabeled Data? Instance Credibility Inference for Few-Shot Learning'', there are results of the proposed ICI with respect to the inductive, transductive and semi-supervised settings, how to run expreiments with the provided codes for different settings?
Thanks.

**Comment by Yikai-Wang** [comment]
Sorry but we do not have permission to re-distribute these datasets. You may open an issue on their repo to request a BaiduNetDisk link.

For the running code of different settings, please check the [readme](https://github.com/Yikai-Wang/ICI-FSL/tree/master/V2-TPAMI#testing).

**Comment by Johnzhjw** [comment]
Thank you very much.
