### ISSUE TITLE
Hello, where are the csv files needed in code?

### ISSUE THREAD

**Issue by Willforcv** [Yikai-Wang/ICI-FSL#2]
thanks ~

**Comment by Yikai-Wang** [comment]
We suggest to create your own csv file to match the path in your machine.
In the csv file, each line is related to one image where the first column is the path and the second column is the category/label.
You may check/modify the code in:
https://github.com/Yikai-Wang/ICI-FSL/blob/0d6a3e5b3403a8a3d8f22b04f91406fa4650fd97/datasets.py#L19-L35

**Comment by Willforcv** [comment]
> We suggest to create your own csv file to match the path in your machine.
> In the csv file, each line is related to one image where the first column is the path and the second column is the category/label.
> You may check/modify the code in:
> https://github.com/Yikai-Wang/ICI-FSL/blob/0d6a3e5b3403a8a3d8f22b04f91406fa4650fd97/datasets.py#L19-L35

ok, thanks>!

**Comment by songquanpeng** [comment]
> We suggest to create your own csv file to match the path in your machine.
> In the csv file, each line is related to one image where the first column is the path and the second column is the category/label.
> You may check/modify the code in:
> https://github.com/Yikai-Wang/ICI-FSL/blob/0d6a3e5b3403a8a3d8f22b04f91406fa4650fd97/datasets.py#L19-L35

Hello, @Yikai-Wang could you please upload a sample CSV file for us to reference? Really appreciate it!

**Comment by Yikai-Wang** [comment]
> Hello, @Yikai-Wang could you please upload a sample CSV file for us to reference? Really appreciate it!

The csv file should be something like this (with two columns and several rows):
| filename              | label     |
| --------------------- | --------- |
| n0153282900000005.jpg | n01532829 |
| n0153282900000006.jpg | n01532829 |
| n0153282900000007.jpg | n01532829 |
| n0153282900000010.jpg | n01532829 |

**Comment by songquanpeng** [comment]
> > Hello, @Yikai-Wang could you please upload a sample CSV file for us to reference? Really appreciate it!
> 
> The csv file should be something like this (with two columns and several rows):
> 
> filename	label
> n0153282900000005.jpg	n01532829
> n0153282900000006.jpg	n01532829
> n0153282900000007.jpg	n01532829
> n0153282900000010.jpg	n01532829

Thanks for your reply. BTW, I wrote a simple script to help generate those specified CSV files: [generate_required_csv.py](https://github.com/songquanpeng/ICI-FSL/blob/master/data/miniimagenet/images-lc/generate_required_csv.py), hope it helpful for other guys.
