### ISSUE TITLE
about trained model in dir  'ICI-FSL/ckpt'

### ISSUE THREAD

**Issue by xiaofeng-github** [Yikai-Wang/ICI-FSL#5]
hello, the saved models in dir  'ICI-FSL/ckpt' are best_model for correspondent dataset?

**Comment by Yikai-Wang** [comment]
The saved models are selected by 
https://github.com/Yikai-Wang/ICI-FSL/blob/f2537b7742159adfa68cc8646b9a20c570320443/main.py#L75-L80
with the best accuracy on the test set of base classes (split by EmbeddingDataset).
